"""Canonical logical evidence and provider mappings."""

from __future__ import annotations

from obrm.evidence.models import (
    EVIDENCE_STATUS_MISSING,
    EVIDENCE_STATUS_PLANNED,
    EVIDENCE_STATUS_RESEARCH,
    EVIDENCE_STATUS_VALIDATED,
    PROVIDER_STATUS_AVAILABLE,
    PROVIDER_STATUS_CANDIDATE,
    PROVIDER_STATUS_FORBIDDEN,
    PROVIDER_STATUS_FUTURE,
    PROVIDER_STATUS_VALIDATED,
    EvidenceItem,
    EvidenceProviderMapping,
)


EVIDENCE_REGISTRY: tuple[EvidenceItem, ...] = (
    EvidenceItem(
        key="realized_valuation",
        display_name="Realized Valuation",
        domain="On-Chain",
        intended_dimension="On-Chain",
        purpose="Compare Bitcoin market value with aggregate realized value.",
        status=EVIDENCE_STATUS_VALIDATED,
        required_for_dimension=True,
        documentation="docs/handbook/11_Validated_OnChain_Research.md",
        target_version="0.9.3",
    ),
    EvidenceItem(
        key="network_strength",
        display_name="Network Strength",
        domain="On-Chain",
        intended_dimension="On-Chain",
        purpose="Describe mining commitment and network security activity.",
        status=EVIDENCE_STATUS_VALIDATED,
        required_for_dimension=True,
        documentation="docs/handbook/11_Validated_OnChain_Research.md",
        target_version="0.9.3",
    ),
    EvidenceItem(
        key="holder_behaviour",
        display_name="Holder Behaviour",
        domain="On-Chain",
        intended_dimension="On-Chain",
        purpose="Describe dormancy, spending behaviour, and long-term holder conviction.",
        status=EVIDENCE_STATUS_RESEARCH,
        required_for_dimension=True,
        documentation="docs/handbook/16_Holder_Behaviour_Research.md",
        target_version="0.10.2",
    ),
    EvidenceItem(
        key="realized_capital_flow",
        display_name="Realized Capital Flow",
        domain="On-Chain",
        intended_dimension="On-Chain",
        purpose="Describe realized-cap growth and capital entering or leaving Bitcoin.",
        status=EVIDENCE_STATUS_RESEARCH,
        required_for_dimension=True,
        documentation="docs/handbook/17_Realized_Capital_Flow_Research.md",
        target_version="0.10.3",
    ),
    EvidenceItem(
        key="market_liquidity",
        display_name="Market Liquidity",
        domain="Liquidity",
        intended_dimension="Macro / Liquidity",
        purpose="Describe the availability and direction of market liquidity.",
        status=EVIDENCE_STATUS_PLANNED,
        required_for_dimension=False,
        documentation="docs/handbook/14_Evidence_Registry.md",
        target_version="post-1.0",
    ),
    EvidenceItem(
        key="macro_regime",
        display_name="Macro Regime",
        domain="Macro",
        intended_dimension="Macro / Liquidity",
        purpose="Describe rates, currency strength, and broad monetary conditions.",
        status=EVIDENCE_STATUS_PLANNED,
        required_for_dimension=False,
        documentation="docs/handbook/14_Evidence_Registry.md",
        target_version="post-1.0",
    ),
    EvidenceItem(
        key="derivatives_positioning",
        display_name="Derivatives Positioning",
        domain="Market Structure",
        intended_dimension="Market Structure",
        purpose="Describe leverage, funding, open interest, and liquidation pressure.",
        status=EVIDENCE_STATUS_PLANNED,
        required_for_dimension=False,
        documentation="docs/handbook/14_Evidence_Registry.md",
        target_version="post-1.0",
    ),
    EvidenceItem(
        key="market_sentiment",
        display_name="Market Sentiment",
        domain="Sentiment",
        intended_dimension="Sentiment",
        purpose="Describe broad market emotion without replacing objective evidence.",
        status=EVIDENCE_STATUS_PLANNED,
        required_for_dimension=False,
        documentation="docs/handbook/14_Evidence_Registry.md",
        target_version="post-1.0",
    ),
)


PROVIDER_MAPPINGS: tuple[EvidenceProviderMapping, ...] = (
    EvidenceProviderMapping(
        evidence_key="realized_valuation",
        provider="Coin Metrics Community",
        provider_metric="CapMVRVCur",
        status=PROVIDER_STATUS_VALIDATED,
        definition="Current market capitalization divided by realized capitalization.",
        provenance_note="Empirically validated through the Community API in v0.9.x.",
        priority=10,
    ),
    EvidenceProviderMapping(
        evidence_key="network_strength",
        provider="Coin Metrics Community",
        provider_metric="HashRate",
        status=PROVIDER_STATUS_VALIDATED,
        definition="Estimated Bitcoin network hash rate.",
        provenance_note="Empirically validated through the Community API in v0.9.x.",
        priority=10,
    ),
    EvidenceProviderMapping(
        evidence_key="holder_behaviour",
        provider="Portable Research CSV",
        provider_metric="User-selected reviewed daily metric",
        status=PROVIDER_STATUS_AVAILABLE,
        definition=(
            "Provider-neutral dormancy, coin-days-destroyed, long-term-holder "
            "supply, dormant-supply, or documented distribution evidence."
        ),
        provenance_note=(
            "v0.10.2 import pipeline requires definition, licence, source, "
            "canonical schema validation, and a dataset hash."
        ),
        priority=15,
    ),
    EvidenceProviderMapping(
        evidence_key="holder_behaviour",
        provider="Alternative free provider",
        provider_metric=None,
        status=PROVIDER_STATUS_CANDIDATE,
        definition="Dormancy, spent-output, coin-age, or long-term-holder evidence.",
        provenance_note="Provider discovery remains open for an automated source adapter.",
        priority=20,
    ),
    EvidenceProviderMapping(
        evidence_key="holder_behaviour",
        provider="Bitcoin Core",
        provider_metric=None,
        status=PROVIDER_STATUS_FUTURE,
        definition="Self-computed UTXO age and spending behaviour.",
        provenance_note="Maximum-transparency v2.0 research path.",
        priority=100,
    ),
    EvidenceProviderMapping(
        evidence_key="realized_capital_flow",
        provider="Coin Metrics Community",
        provider_metric="CapRealUSD",
        status=PROVIDER_STATUS_FORBIDDEN,
        definition="Realized capitalization in US dollars.",
        provenance_note="Catalogue entry exists, but Community API access returned HTTP 403.",
        priority=50,
    ),
    EvidenceProviderMapping(
        evidence_key="realized_capital_flow",
        provider="Portable Research CSV",
        provider_metric="User-selected reviewed daily metric",
        status=PROVIDER_STATUS_AVAILABLE,
        definition="Realized-cap growth/change, realized value flow, capital inflow/outflow, net flow, exchange netflow, or a documented custom capital-flow metric.",
        provenance_note="v0.10.3 requires definition, licence, source, direction semantics, canonical schema validation, and SHA-256 integrity verification.",
        priority=15,
    ),
    EvidenceProviderMapping(
        evidence_key="realized_capital_flow",
        provider="Bitcoin Core",
        provider_metric=None,
        status=PROVIDER_STATUS_FUTURE,
        definition="Self-computed realized capitalization and realized-cap change.",
        provenance_note="Maximum-transparency v2.0 research path.",
        priority=100,
    ),
)
